version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend
  
hooks:
  BeforeInstall:
      - location: before_install.sh
        timeout: 300
  AfterInstall:
      - location: after_install.sh
        timeout: 300
