version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/textpro
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
      - location: before_install.sh
        runas: root
        timeout: 300
  AfterInstall:
      - location: after_install.sh
        runas: root
        timeout: 300

